### PR TITLE
boulder: improve boulder new error handling for `boulder new`

### LINKED ISSUE #511: boulder new: Adding monitoring file should not fail if website resource cannot be reached
e.g.
```
 - Extracting https://download.gimp.org/gimp/help/gimp-help-3.0.0.tar.bz2                                                                                                                                                                         Detected type: application/x-bzip2 (bz2)
Fetched https://download.gimp.org/gimp/help/gimp-help-3.0.0.tar.bz2

Monitoring | Matched id 1162 from gimp-help
Error: recipe: draft: monitoring: statuscode: error sending request for url (https://cpe-guesser.cve-search.org/search): operation timed out
```

As https://cpe-guesser.cve-search.org was down at the time, the monitoring file did not get written to disk.

### PR DESCRIPTION
**Pull request by barne856**
Closes #511 

## Summary of Changes

- For requests to release-monitoring.org and cpe-guesser.cve-search.org, HTTP errors and connection failures now show warnings and continue with empty response instead of crashing
- Informative comments included in the `monitoring.yaml` based on failure type for CPE failures:
  - Service errors: `# CPE service returned error, retry later <date>`
  - Connection failed: `# CPE service unreachable, retry later <date>`
  - No results: `# No CPE found, last checked <date>`

I've tested this by blocking access to the sites and running boulder new on the abseil-cpp project:

```bash
boulder new https://github.com/abseil/abseil-cpp/releases/download/20250512.1/abseil-cpp-20250512.1.tar.gz
```

With release-monitoring.org inaccessible:

```bash
 ■ Extracting https://github.com/abseil/abseil-cpp/releases/download/20250512.1/abseil-cpp-20250512.1.tar.gz                               Detected type: application/gzip (gz)
Fetched https://github.com/abseil/abseil-cpp/releases/download/20250512.1/abseil-cpp-20250512.1.tar.gz

Warning | Monitoring service is inaccessible
Warning | Find the correct ID for the project at https://release-monitoring.org/

Saved stone.yaml & monitoring.yaml to "."
```

```yml
releases:
  id: ~ # https://release-monitoring.org/ and use the numeric id in the url of project
  rss: https://github.com/abseil/abseil-cpp/releases.atom
security:
  cpe: ~ # No CPE found, last checked 2025-08-09
```

With cpe-guesser.cve-search.org inaccessible:

```bash
 ■ Extracting https://github.com/abseil/abseil-cpp/releases/download/20250512.1/abseil-cpp-20250512.1.tar.gz                               Detected type: application/gzip (gz)
Fetched https://github.com/abseil/abseil-cpp/releases/download/20250512.1/abseil-cpp-20250512.1.tar.gz

Monitoring | Matched id 115295 from abseil-cpp
Warning | CPE service is inaccessible

Saved stone.yaml & monitoring.yaml to "."
```

```yml
releases:
  id: 115295
  rss: https://github.com/abseil/abseil-cpp/releases.atom
security:
  cpe: ~ # CPE service unreachable, retry later 2025-08-09
```

### CODE REVIEW

File: boulder/src/draft/monitoring.rs [hunk 1]
```diff
@@ -58,31 +58,48 @@ impl<'a> Monitoring<'a> {
...
+        let body = match client.get(&url).send() {
+            Ok(resp) => match resp.error_for_status_ref() {
+                Ok(_) => resp.json()?,
+                Err(resp_err) => {
+                    // response error, maybe HTTP 5xx or 4xx?
+                    let status = resp_err
+                        .status()
+                        .map(|s| s.to_string())
+                        .unwrap_or_else(|| "unknown".to_owned());
+                    println!("{} | Monitoring service returned error: {status}", "Warning".yellow(),);
```
Comment (jplatte) [inline boulder/src/draft/monitoring.rs]:
```suggestion
                    println!("{} | Monitoring service returned error: {status}", "Warning".yellow());
```

File: boulder/src/draft/monitoring.rs [hunk 2]
```diff
@@ -58,31 +58,48 @@ impl<'a> Monitoring<'a> {
...
+                    Response {
+                        items: Vec::new(),
+                        total_items: 0,
+                    }
+                }
+            },
+            Err(_) => {
+                // request error, maybe site is inaccessible?
+                println!("{} | Monitoring service is inaccessible", "Warning".yellow(),);
```
Comment (jplatte) [inline boulder/src/draft/monitoring.rs]:
```suggestion
                println!("{} | Monitoring service is inaccessible", "Warning".yellow());
```

File: boulder/src/draft/monitoring.rs [hunk 3]
```diff
@@ -118,20 +135,38 @@ impl<'a> Monitoring<'a> {
...
+                    let json: Vec<Vec<Value>> = serde_json::from_str(&resp.text()?).unwrap_or_default();
+                    (json, "searched")
+                }
+                Err(resp_err) => {
+                    // response error, maybe HTTP 5xx or 4xx?
+                    let status = resp_err
+                        .status()
+                        .map(|s| s.to_string())
+                        .unwrap_or_else(|| "unknown".to_owned());
+                    println!("{} | CPE service returned an error: {status}", "Warning".yellow(),);
```
Comment (jplatte) [inline boulder/src/draft/monitoring.rs]:
```suggestion
                    println!("{} | CPE service returned an error: {status}", "Warning".yellow());
```

File: boulder/src/draft/monitoring.rs [hunk 4]
```diff
@@ -118,20 +135,38 @@ impl<'a> Monitoring<'a> {
...
+                    (Vec::new(), "service_error")
+                }
+            },
+            Err(_) => {
+                // request error, maybe site is inaccessible?
+                println!("{} | CPE service is inaccessible", "Warning".yellow(),);
```
Comment (jplatte) [inline boulder/src/draft/monitoring.rs]:
```suggestion
                println!("{} | CPE service is inaccessible", "Warning".yellow());
```

File: boulder/src/draft/monitoring.rs [hunk 5]
```diff
@@ -215,10 +256,20 @@ impl<'a> Monitoring<'a> {
             let cpe_string = "cpe: []";
             let cpe_marker = yaml_string.find(cpe_string).expect("security cpe marker not found");
             yaml_string = yaml_string.replace(cpe_string, "cpe: ~");
-            let cpe_help_text = format!(
-                " # Last checked {}",
-                chrono::Local::now().date_naive().format("%Y-%m-%d")
-            );
+            let cpe_help_text = match cpe_search_status.as_str() {
+                "service_error" => format!(
+                    " # CPE service returned error, retry later {}",
```
Comment (jplatte) [inline boulder/src/draft/monitoring.rs]:
```suggestion
                    " # CPE service returned error, retry later ({})",
```

File: boulder/src/draft/monitoring.rs [hunk 6]
```diff
@@ -215,10 +256,20 @@ impl<'a> Monitoring<'a> {
...
+                    chrono::Local::now().date_naive().format("%Y-%m-%d")
+                ),
+                "connection_failed" => format!(
+                    " # CPE service unreachable, retry later {}",
+                    chrono::Local::now().date_naive().format("%Y-%m-%d")
+                ),
+                _ => format!(
+                    " # No CPE found, last checked {}",
```
Comment (jplatte) [inline boulder/src/draft/monitoring.rs]:
```suggestion
                    " # No CPE found, last checked ({})",
```

File: boulder/src/draft/monitoring.rs [hunk 7]
```diff
@@ -215,10 +256,20 @@ impl<'a> Monitoring<'a> {
...
-                " # Last checked {}",
-                chrono::Local::now().date_naive().format("%Y-%m-%d")
-            );
+            let cpe_help_text = match cpe_search_status.as_str() {
+                "service_error" => format!(
+                    " # CPE service returned error, retry later {}",
+                    chrono::Local::now().date_naive().format("%Y-%m-%d")
+                ),
+                "connection_failed" => format!(
+                    " # CPE service unreachable, retry later {}",
```
Comment (jplatte) [inline boulder/src/draft/monitoring.rs]:
```suggestion
                    " # CPE service unreachable, retry later ({})",
```

**Review by jplatte — COMMENTED** [review]
This is great! Got some formatting nitpicks, and one question (also about formatting 😄): do we print `Warning | Message` anywhere else? I would think its usually `Warning: Message` but don't actually know. I think both look fine, just want us to be consistent 🙂

**Comment by barne856** [comment]
> This is great! Got some formatting nitpicks, and one question (also about formatting 😄): do we print `Warning | Message` anywhere else? I would think its usually `Warning: Message` but don't actually know. I think both look fine, just want us to be consistent 🙂

Searching through the code I see one other file that does use this format `boulder/src/draft.rs`, other than that is is just this file (and there are existing messages using the same format in the file). Moss seems to use `warn!` which I think would print to stderr. The distinction is these messages are meant for user-facing informational warnings and not internal logging / debugging.

**Review by jplatte — APPROVED** [review]
